name: flutter_releaser_cli
description: A command-line interface for Flutter Releaser, providing tools for managing and automating Flutter app releases.
version: 0.0.5+2
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0

dependencies:
  pub_semver: ^2.2.0
  archive: ^4.0.7
  path: ^1.9.1
  crypto: ^3.0.6
  pubspec_parse: ^1.5.0
  pub_updater: ^0.5.0
  args: ^2.7.0
  flutter_releaser: ^0.3.4+2
  talker: ^5.0.2
  cli_launcher: ^0.3.2+1
  flutter_releaser_dio: ^0.1.1+5
  dio: ^5.9.0
