name: flutter_releaser_dio
description: Dio implementation for flutter_releaser package, providing Dio-based release checking and downloading capabilities for Flutter applications.
version: 0.1.1+4
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0

dependencies:
  flutter_releaser: ^0.3.4+1
  dio: ^5.9.0
