name: flutter_releaser_widgets
description: "Custom Flutter widgets for displaying update dialogs, notifications, and other UI components related to application updates using flutter_releaser."
version: 0.0.2
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/
publish_to: "none"

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_releaser: ^0.3.3
  forui: 0.17.0
