name: flutter_releaser_flutter
description: Flutter-friendly interface for the flutter_releaser package with reactive state management for desktop application updates
version: 0.1.2+2
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_releaser: ^0.3.4
  package_info_plus: ^9.0.0

  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterReleaserFlutterPlugin
      macos:
        pluginClass: FlutterReleaserFlutterPlugin
      windows:
        pluginClass: FlutterReleaserFlutterPluginCApi
