name: flutter_releaser_desktop
description: "Flutter Releaser desktop application to download/upload/test your flutter applications' updates."
publish_to: 'none'
version: 1.0.0
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_releaser: ^0.3.2
  flutter_releaser_dio: ^0.1.1+1
  flutter_releaser_flutter: ^0.1.2
  package_info_plus: ^9.0.0
  dio: ^5.9.0
  talker: ^5.0.2

flutter:
  uses-material-design: true
